name: Docker Image Scan Template

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build Docker image
      #   run: ls -lrt && docker build -t ${{ inputs.image-name }} ${{ inputs.dockerfile-path }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{ inputs.image-name }}:latest

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-name }}:latest
          format: 'html'
          output: 'trivy-report.html'

      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-report.html
