name: Docker Image Scan Template

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: ls -lrt && docker build -t ${{ inputs.image-name }} ${{ inputs.dockerfile-path }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ${{ inputs.dockerfile-path }}
      #     #push: true
      #     tags: ${{ inputs.image-name }}:latest

      - name: Save Docker image to file
        run: docker save ${{ inputs.image-name }}:latest -o ${{ inputs.image-name }}.tar

      - name: Install OpenSCAP
        run: sudo apt-get update && sudo apt-get install -y libopenscap8 


      - name: Scan Docker image with OpenSCAP
        run: |
          oscap xccdf eval --profile xccdf_mil.disa.stig_profile_MAC-2_Sensitive --results results.xml --report report.html U_RHEL_8_V1R8_STIG_SCAP_1-2_Benchmark_ARMEDIA.xml ${{ inputs.image-name }}.tar

      - name: Upload OpenSCAP scan results
        uses: actions/upload-artifact@v3
        with:
          name: oscap-report
          path: report.html

      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.53.0/trivy_0.53.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.53.0_Linux-64bit.deb

      - name: Scan Docker image with Trivy
        run: trivy image ${{ inputs.image-name }}

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.html
